GET http://127.0.0.1:8000/water/0/container/states/1
Accept: application/json

###
#{
#    "count": 6,
#    "next": null,
#    "previous": null,
#    "results": [
#        {
#            "container_state": 20,
#            "container": {
#                "id": 1,
#                "station": {
#                    "id": 0,
#                    "descriptive_location": "main location"
#                },
#                "container_id": 1
#            },
#            "timestamp": "2020-02-23T19:33:30.098138Z"
#        },
#        {
#            "container_state": 20,
#            "container": {
#                "id": 1,
#                "station": {
#                    "id": 0,
#                    "descriptive_location": "main location"
#                },
#                "container_id": 1
#            },
#            "timestamp": "2020-02-23T19:36:13.015063Z"
#        },
#        {
#            "container_state": 20,
#            "container": {
#                "id": 1,
#                "station": {
#                    "id": 0,
#                    "descriptive_location": "main location"
#                },
#                "container_id": 1
#            },
#            "timestamp": "2020-02-23T19:36:17.916495Z"
#        },
#        {
#            "container_state": 20,
#            "container": {
#                "id": 1,
#                "station": {
#                    "id": 0,
#                    "descriptive_location": "main location"
#                },
#                "container_id": 1
#            },
#            "timestamp": "2020-02-23T19:36:34.691965Z"
#        },
#        {
#            "container_state": 20,
#            "container": {
#                "id": 1,
#                "station": {
#                    "id": 0,
#                    "descriptive_location": "main location"
#                },
#                "container_id": 1
#            },
#            "timestamp": "2020-02-23T19:36:41.208955Z"
#        },
#        {
#            "container_state": 20,
#            "container": {
#                "id": 1,
#                "station": {
#                    "id": 0,
#                    "descriptive_location": "main location"
#                },
#                "container_id": 1
#            },
#            "timestamp": "2020-02-23T19:39:41.573107Z"
#        }
#    ]
#}