#POST http://localhost:80/water/(?P<station_id>\d+)/manual
POST http://localhost:80/water/0/manual
Content-Type: application/json

{
}

###
POST http://localhost:80/api/item
Content-Type: application/json

{
  "valve_id": "1",
  "valve_open": "False"
}

###
#POST http://localhost:80/water/(?P<station_id>\d+)/manual
POST http://localhost:80/water/0/manual
Content-Type: application/json


{
  "pump_id": "1",
  "pump_state": "True"
}


###





