//POST http://127.0.0.1:8000/water/<int:station_id>/stats/
POST http://127.0.0.1:8000/water/1/stats/
Content-Type: application/json

{
  "steering_state": "AU",
  "timestamp": "2020-02-23T23:05:34.370047Z",
  "valves": [
    {
      "valve_id": "1",
      "valve_open": "True"
    },
    {
      "valve_id": "2",
      "valve_open": "True"
    }
  ],
  "containers": [
    {
      "container_id": "1",
      "container_state": "20"
    },
    {
      "container_id": "2",
      "container_state": "80"
    }
  ],
  "pumps": [
    {
      "pump_id": 1,
      "pump_state": "True"
    },
    {
      "pump_id": 2,
      "pump_state": "False"
    }
  ]
}

###
