GET http://127.0.0.1:8000/water/1/states
Accept: application/json

###
#HTTP/1.1 200 OK
#Date: Mon, 24 Feb 2020 13:30:00 GMT
#Server: WSGIServer/0.2 CPython/3.8.1
#Content-Type: application/json
#Vary: Accept, Cookie
#Allow: GET, POST, HEAD, OPTIONS
#X-Frame-Options: DENY
#Content-Length: 1348
#X-Content-Type-Options: nosniff
#
#{
#  "count": 44,
#  "next": "http://127.0.0.1:8000/water/1/states/?page=2",
#  "previous": null,
#  "results": [
#    {
#      "steering_state": "AU",
#      "manual_steering_user": {
#        "id": 1,
#        "username": "admin",
#        "first_name": "",
#        "last_name": "",
#        "email": ""
#      },
#      "timestamp": "2020-02-24T00:08:53.243522+01:00"
#    },
#    {
#      "steering_state": "ON",
#      "manual_steering_user": {
#        "id": 1,
#        "username": "admin",
#        "first_name": "",
#        "last_name": "",
#        "email": ""
#      },
#      "timestamp": "2020-02-24T00:05:34.370047+01:00"
#    },
#    {
#      "steering_state": "ON",
#      "manual_steering_user": {
#        "id": 3,
#        "username": "student",
#        "first_name": "",
#        "last_name": "",
#        "email": ""
#      },
#      "timestamp": "2020-02-24T00:04:41.066983+01:00"
#    },
#    {
#      "steering_state": "ON",
#      "manual_steering_user": {
#        "id": 3,
#        "username": "student",
#        "first_name": "",
#        "last_name": "",
#        "email": ""
#      },
#      "timestamp": "2020-02-23T23:41:51.056626+01:00"
#    },
#    {
#      "steering_state": "ON",
#      "manual_steering_user": null,
#      "timestamp": "2020-02-23T23:39:55.787220+01:00"
#    },
#    {
#      "steering_state": "ON",
#      "manual_steering_user": null,
#      "timestamp": "2020-02-23T23:39:12.338122+01:00"
#    },
#    {
#      "steering_state": "ON",
#      "manual_steering_user": null,
#      "timestamp": "2020-02-23T23:34:58.674377+01:00"
#    },
#    {
#      "steering_state": "AU",
#      "manual_steering_user": null,
#      "timestamp": "2020-02-23T23:08:23.290000+01:00"
#    },
#    {
#      "steering_state": "AU",
#      "manual_steering_user": null,
#      "timestamp": "2020-02-23T23:08:23.290000+01:00"
#    },
#    {
#      "steering_state": "AU",
#      "manual_steering_user": null,
#      "timestamp": "2020-02-23T23:06:46.893000+01:00"
#    }
#  ]
#}