GET http://127.0.0.1:8000/water/1/valve/1/states/
Accept: application/json

###
#HTTP/1.1 200 OK
#Date: Mon, 24 Feb 2020 13:34:45 GMT
#Server: WSGIServer/0.2 CPython/3.8.1
#Content-Type: application/json
#Vary: Accept, Cookie
#Allow: GET, POST, HEAD, OPTIONS
#X-Frame-Options: DENY
#Content-Length: 673
#X-Content-Type-Options: nosniff
#
#{
#  "count": 10,
#  "next": null,
#  "previous": null,
#  "results": [
#    {
#      "valve_open": true,
#      "timestamp": "2020-02-23T23:08:53.243522Z"
#    },
#    {
#      "valve_open": true,
#      "timestamp": "2020-02-23T23:05:34.370047Z"
#    },
#    {
#      "valve_open": true,
#      "timestamp": "2020-02-23T23:04:41.066983Z"
#    },
#    {
#      "valve_open": true,
#      "timestamp": "2020-02-23T22:39:55.787220Z"
#    },
#    {
#      "valve_open": true,
#      "timestamp": "2020-02-23T22:39:12.338122Z"
#    },
#    {
#      "valve_open": true,
#      "timestamp": "2020-02-11T02:18:27.327903Z"
#    },
#    {
#      "valve_open": true,
#      "timestamp": "2020-02-11T02:17:55.851148Z"
#    },
#    {
#      "valve_open": true,
#      "timestamp": "2020-02-11T02:17:25.879150Z"
#    },
#    {
#      "valve_open": true,
#      "timestamp": "2020-02-11T02:16:32.518546Z"
#    },
#    {
#      "valve_open": false,
#      "timestamp": "2020-02-11T01:25:47.939000Z"
#    }
#  ]
#}